### ISSUE TITLE
Add today's date

### ISSUE THREAD

**Issue by icaoberg** [icaoberg/sams2024-fair#15]
https://github.com/icaoberg/sams2024-fair/blob/7202a7a71e7bd1aeba1f4b694bad1087304d71b7/streamlit_app.py#L17

Modify this line to reflect today's date programmatically. 

You can

| Method                         | Code                                                                           | Output Format |
|--------------------------------|--------------------------------------------------------------------------------|---------------|
| Using `datetime` module        | ```from datetime import date today = date.today()```                      | `YYYY-MM-DD`  |
| Using `datetime` with formatting | ```from datetime import datetime today = datetime.now().strftime('%Y-%m-%d')``` | `YYYY-MM-DD`  |
| Using `time` module            | ```import time today = time.strftime('%Y-%m-%d')```                       | `YYYY-MM-DD`  |
| Using `pandas`                 | ```import pandas as pd today = pd.Timestamp.now().strftime('%Y-%m-%d')``` | `YYYY-MM-DD`  |

**Comment by icaoberg** [comment]
@Gaelm949  if you want to include the hour you could use

```
| Method                         | Code                                                                                          | Output Format     |
|--------------------------------|-----------------------------------------------------------------------------------------------|-------------------|
| Using `datetime` module        | ```python from datetime import datetime today = datetime.now() print(today)```                  | `YYYY-MM-DD HH:MM:SS` |
| Using `datetime` with formatting | ```python from datetime import datetime today = datetime.now().strftime('%Y-%m-%d %H:%M:%S')``` | `YYYY-MM-DD HH:MM:SS` |
| Using `time` module            | ```python import time today = time.strftime('%Y-%m-%d %H:%M:%S')```                            | `YYYY-MM-DD HH:MM:SS` |
| Using `pandas`                 | ```python import pandas as pd today = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')```      | `YYYY-MM-DD HH:MM:SS` |
```

**Comment by vrubiom** [comment]
from datetime import date today = date.today()
```python from datetime import datetime today = datetime.now() print(today)```
today = 'Today''s date'
st.write(today)
